artifact_uri: file:///Users/macbookair/Desktop/proyecto 2/mlruns_regresion/255136500529534988/da7844a8b75a47d9a379d7833c5dcf55/artifacts
end_time: 1764374826017
entry_point_name: ''
experiment_id: '255136500529534988'
lifecycle_stage: active
run_id: da7844a8b75a47d9a379d7833c5dcf55
run_name: RUN_DNN_REGRESION 3
source_name: ''
source_type: 4
source_version: ''
start_time: 1764374619575
status: 3
tags: []
user_id: macbookair
