artifact_location: file:///Users/macbookair/Desktop/proyecto 2/mlruns_regresion/0
creation_time: 1764373002365
experiment_id: '0'
last_update_time: 1764373002365
lifecycle_stage: active
name: Default
